### ISSUE TITLE
Obtaining absolute timestamps

### ISSUE THREAD

**Issue by manurare** [serg3y/MatLab-digiCamControl#1]
Hi,

Is it possible to obtain the absolute time stamps for each sampled frame?

**Comment by serg3y** [comment]
There are two clocks, the computer clock which is simply the time when you send the command to capture and camera clock which goes into the image exif header.
Depending on if you computer is regularly syncing time with internet or if your camera is syncing using GPS receiver will determine which clock is more accurate...

On 15 Feb. 2020 08:26, manurare <notifications@github.com> wrote:

Hi,

Is it possible to obtain the absolute time stamps for each sampled frame?

**Comment by manurare** [comment]
Let me explain better. What I am trying to do is each time C.cmd('StartRecord') is triggered I would like to save for each frame on the video its correspondent absolute time. Therefore, if my video is 100 frames long I will have a vector of 100 absolute time elements. I tried to get into the code the problem is that  C.cmd('StartRecord') calls a system instruction to digicamcontrol and I dont know how I can get the timestamps. It is easy with C.Capture as you can execute afterwards 
`datestr(new,'HH:MM:SS.FFF')`
but in the video case is not the same. I thought that internally C.cmd('StartRecord') called N times C.Capture but I was wrong.

Do you have any idea how to implement this behaviour?

**Comment by serg3y** [comment]
For an actual video recording, you would need to download the video and get the time of each frame (in elapsed seconds since start of file) using something like MatLab's VideoReader. You would then add that to the absolute time which should be part of the exif data in that file to get absolute time for each frame...

I don't think digicam can query the camera for this sort of information without downloading the video file.

On Mon, 17 Feb 2020 at 19:28, manurare <notifications@github.com<mailto:notifications@github.com>> wrote:

Let me explain better. What I am trying to do is each time C.cmd('StartRecord') is triggered I would like to save for each frame on the video its correspondent absolute time. Therefore, if my video is 100 frames long I will have a vector of 100 absolute time elements. I tried to get into the code the problem is that C.cmd('StartRecord') calls a system instruction to digicamcontrol and I dont know how I can get the timestamps. It is easy with C.Capture as you can execute afterwards
datestr(new,'HH:MM:SS.FFF')
but in the video case is not the same. I thought that internally C.cmd('StartRecord') called N times C.Capture but I was wrong.

Do you have any idea how to implement this behaviour?

**Comment by manurare** [comment]
Ok! thanks!
